#!/usr/bin/env python3
"""
Test script to validate the --label-no-box option functionality.
Tests that the generated plotting script contains labels without bbox when flag is used.
"""

import sys
import os
import subprocess
import tempfile
import re

def test_label_with_box():
    """Test that labels WITH box are generated by default (when --label-no-box is not used)."""
    with tempfile.NamedTemporaryFile(mode='w', suffix='.dat', delete=False) as f:
        output_file = f.name
    
    plot_script = output_file.replace('.dat', '_plot.py')
    
    try:
        # Run command without --label-no-box
        cmd = [
            sys.executable,
            'avgpos.py',
            'example/POSCAR',
            '-s', 'Se',
            '-d', 'z',
            '-o', output_file,
            '--labels',
            '--plot'
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"FAILED: Command failed with return code {result.returncode}")
            print(f"STDERR: {result.stderr}")
            return False
        
        # Check that plot script was generated
        if not os.path.exists(plot_script):
            print(f"FAILED: Plot script {plot_script} was not generated")
            return False
        
        # Read plot script and verify it contains bbox parameter
        with open(plot_script, 'r') as f:
            script_content = f.read()
        
        # Check for bbox parameter in the script
        if 'bbox=dict(' in script_content:
            print("PASSED: Labels with box (default behavior)")
            return True
        else:
            print("FAILED: bbox parameter not found in generated script")
            return False
    
    finally:
        # Clean up
        if os.path.exists(output_file):
            os.remove(output_file)
        if os.path.exists(plot_script):
            os.remove(plot_script)


def test_label_no_box():
    """Test that labels WITHOUT box are generated when --label-no-box is used."""
    with tempfile.NamedTemporaryFile(mode='w', suffix='.dat', delete=False) as f:
        output_file = f.name
    
    plot_script = output_file.replace('.dat', '_plot.py')
    
    try:
        # Run command with --label-no-box
        cmd = [
            sys.executable,
            'avgpos.py',
            'example/POSCAR',
            '-s', 'Se',
            '-d', 'z',
            '-o', output_file,
            '--labels',
            '--plot',
            '--label-no-box'
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"FAILED: Command failed with return code {result.returncode}")
            print(f"STDERR: {result.stderr}")
            return False
        
        # Check that plot script was generated
        if not os.path.exists(plot_script):
            print(f"FAILED: Plot script {plot_script} was not generated")
            return False
        
        # Read plot script and verify it does NOT contain bbox parameter
        with open(plot_script, 'r') as f:
            script_content = f.read()
        
        # Check that bbox parameter is NOT in the script
        if 'bbox=dict(' not in script_content:
            # Also verify that labels are still being added
            if 'ax.annotate(labels[i]' in script_content:
                print("PASSED: Labels without box (--label-no-box flag)")
                return True
            else:
                print("FAILED: Labels are not being added at all")
                return False
        else:
            print("FAILED: bbox parameter found in generated script (should not be present)")
            return False
    
    finally:
        # Clean up
        if os.path.exists(output_file):
            os.remove(output_file)
        if os.path.exists(plot_script):
            os.remove(plot_script)


def test_label_no_box_without_labels():
    """Test that --label-no-box has no effect when --labels is not used."""
    with tempfile.NamedTemporaryFile(mode='w', suffix='.dat', delete=False) as f:
        output_file = f.name
    
    plot_script = output_file.replace('.dat', '_plot.py')
    
    try:
        # Run command with --label-no-box but WITHOUT --labels
        cmd = [
            sys.executable,
            'avgpos.py',
            'example/POSCAR',
            '-s', 'Se',
            '-d', 'z',
            '-o', output_file,
            '--plot',
            '--label-no-box'
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            print(f"FAILED: Command failed with return code {result.returncode}")
            print(f"STDERR: {result.stderr}")
            return False
        
        # Check that plot script was generated
        if not os.path.exists(plot_script):
            print(f"FAILED: Plot script {plot_script} was not generated")
            return False
        
        # Read plot script and verify it does not add labels at all
        with open(plot_script, 'r') as f:
            script_content = f.read()
        
        # Since --labels was not used, there should be no label annotation code
        if 'ax.annotate(labels[i]' not in script_content:
            print("PASSED: --label-no-box has no effect without --labels")
            return True
        else:
            print("FAILED: Labels found in script even though --labels was not used")
            return False
    
    finally:
        # Clean up
        if os.path.exists(output_file):
            os.remove(output_file)
        if os.path.exists(plot_script):
            os.remove(plot_script)


def main():
    """Run all tests."""
    print("Testing --label-no-box option functionality")
    print("=" * 60)
    
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
    
    tests = [
        ("Default behavior (with box)", test_label_with_box),
        ("With --label-no-box flag", test_label_no_box),
        ("--label-no-box without --labels", test_label_no_box_without_labels)
    ]
    
    passed = 0
    failed = 0
    
    for test_name, test_func in tests:
        print(f"\nTest: {test_name}")
        if test_func():
            passed += 1
        else:
            failed += 1
    
    print("\n" + "=" * 60)
    print(f"Results: {passed} passed, {failed} failed")
    
    return 0 if failed == 0 else 1


if __name__ == '__main__':
    sys.exit(main())
